<h3>Indice del glossario</h3>
<ul class="menu">
    <li><a href="#audit">Audit</a></li>
    <li><a href="#asp">ASP</a></li>
    <li><a href="#automazione_forza_vendite">Automazione forza vendite</a></li>
    <li><a href="#automazione_marketing">Automazione Marketing</a></li>
    <li><a href="#b2b">B2B</a></li>
    <li><a href="#b2c">B2C</a></li>
    <li><a href="#base_di_conoscenza">Base di conoscenza</a></li>
    <li><a href="#bpr">BPR</a></li>
    <li><a href="#breakeven_point">Breakeven Point</a></li>
    <li><a href="#client_server">Client/Server</a></li>
    <li><a href="#cluster_virtuale">Cluster Virtuale</a></li>
    <li><a href="#contract_manager">Contract Manager</a></li>
    <li><a href="#crm">CRM</a></li>
    <li><a href="#cscw">CSCW (Groupware)</a></li>
    <li><a href="#csv">CSV</a></li>
    <li><a href="#costumer_service">Costumer Service</a></li>
    <li><a href="#direct_mailing">Direct Mailing</a></li>
    <li><a href="#distretti_industriali">Distretti Industriali</a></li>
    <li><a href="#ebusiness">E-Business</a></li>
    <li><a href="#ecommerce">E-Commerce</a></li>
    <li><a href="#ecrm">E-Crm</a></li>
    <li><a href="#extended_enterprise">EE (Extended Enterprise)</a></li>
    <li><a href="#eprocurement">eProcurement</a></li>
    <li><a href="#erp">ERP(Enterprise Resource Planning)</a></li>
    <li><a href="#esupply">eSupply</a></li>
    <li><a href="#fidelizzazione_clienti">Fidelizzazione Clienti</a></li>
    <li><a href="#follow_up">Follow Up</a></li>
    <li><a href="#grid_computing">Grid Computing</a></li>
    <li><a href="#helpdesk">Help Desk</a></li>
    <li><a href="#housing">Housing</a></li>
    <li><a href="#hosting">Hosting</a></li>
    <li><a href="#interworked_enterprise">IE (Internetworked Enterprise)</a></li>
    <li><a href="#isp">ISP</a></li>
    <li><a href="#key_users">Key Users</a></li>
    <li><a href="#knowledge_base">Knowledge Base</a></li>
    <li><a href="#lead_time">Lead Time</a></li>
    <li><a href="#linguaggi_di_esecuzione_processi">Linguaggi di esecuzione di processi</a></li>
    <li><a href="#linguaggi_di_modellazione_processi">Linguaggi di modellazione di processi</a></li>
    <li><a href="#marketplace">Marketplace</a></li>
    <li><a href="#odbc">ODBC</a></li>
    <li><a href="#olap">OLAP</a></li>
    <li><a href="#opensource">Open Source</a></li>
    <li><a href="#outsourcing">Outsourcing</a></li>
    <li><a href="#pda">PDA</a></li>
    <li><a href="#pipeline">Pipeline</a></li>
    <li><a href="#peer_to_peer">Peer-to-Peer</a></li>
    <li><a href="#pmi">PMI</a></li>
    <li><a href="#procurement">Procurement</a></li>
    <li><a href="#prospect">Prospect</a></li>
    <li><a href="#roi">ROI</a></li>
    <li><a href="#sistema_di_crm">Sistema di CRM</a></li>
    <li><a href="#soa">SOA</a></li>
    <li><a href="#suspect">Suspect</a></li>
    <li><a href="#supply_chain">Supply Chain</a></li>
    <li><a href="#template">Template</a></li>
    <li><a href="#time_sheet">Time Sheet</a></li>
    <li><a href="#uddi">UDDI (Universal Description Discovery and Integration)</a></li>
    <li><a href="#webml">WebML</a></li>
    <li><a href="#web_service">Web Service</a></li>
</ul>
